### ISSUE TITLE
Import and export cause app crash on Android 11

### ISSUE THREAD

**Issue by mateusz-bak** [helloworld1/FreeOTPPlus#154]
When clicking any import or export option app crashes, which is a major problem - no backups.

"Files and media" permission is granted.
App version 2.4 (15) from F-Droid
Android 11
OnePlus 8T

**Comment by meersjo** [comment]
Same issue on Nokia 8.3 / Android 11. It does write a file and seems to briefly return to the interface before crashing. I haven't tested the resulting file yet, but visual inspection seems to look OK and correctly terminated.

**Comment by mateusz-bak** [comment]
@meersjo what is the location of saved file?

**Comment by helloworld1** [comment]
Could be related to https://github.com/helloworld1/FreeOTPPlus/issues/153 will investigate

**Comment by meersjo** [comment]
> @meersjo what is the location of saved file?

Google Drive, in my particular case. However, I am mistaken - the file there is an older one.

I have just tested again with 2.5 (16); issue still there.

**Comment by mateusz-bak** [comment]
Issue present on 2.5 (16) from F-Droid

**Comment by helloworld1** [comment]
What format did you use? Could you try export both JSON and key URI format?

**Comment by mateusz-bak** [comment]
@helloworld1 both json and uri for both import and export cause crash

**Comment by helloworld1** [comment]
That's weird, with issue #153 fixed. I wonder if you are OK to test a debug build with import / export.

**Comment by helloworld1** [comment]
The debug build is here: https://drive.google.com/file/d/1S8YvBuGn_tVFJBgn5hmueQBdjQhV-TOP/view?usp=sharing
This won't overwrite your current app and is a different app names "FreeOtp+ Debug"

**Comment by mateusz-bak** [comment]
@helloworld1 I can, will it be installed alongside release version?

**Comment by helloworld1** [comment]
Right, it can be installed alongside the release build. It has an orange icon instead of blue to differentiate.

**Comment by mateusz-bak** [comment]
Will install, anyway will this help? I connected the phone to pc and run
```
adb logcat
```

and catched this on the release app:

```
09-23 07:35:57.692 27901 27901 D AndroidRuntime: Shutting down VM
09-23 07:35:57.694 27901 27901 E AndroidRuntime: FATAL EXCEPTION: main
09-23 07:35:57.694 27901 27901 E AndroidRuntime: Process: org.liberty.android.freeotpplus, PID: 27901
09-23 07:35:57.694 27901 27901 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CREATE_DOCUMENT cat=[android.intent.category.OPENABLE] typ=application/json (has extras) }
09-23 07:35:57.694 27901 27901 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2258)
09-23 07:35:57.694 27901 27901 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1914)
09-23 07:35:57.694 27901 27901 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:5326)
09-23 07:35:57.694 27901 27901 E AndroidRuntime: 	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:588)
09-23 07:35:57.694 27901 27901 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:5284)
09-23 07:35:57.694 27901 27901 E AndroidRuntime: 	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:574)
09-23 07:35:57.694 27901 27901 E AndroidRuntime: 	at org.fedorahosted.freeotp.ui.MainActivity.createFile(MainActivity.kt:371)
09-23 07:35:57.694 27901 27901 E AndroidRuntime: 	at org.fedorahosted.freeotp.ui.MainActivity.onOptionsItemSelected(MainActivity.kt:211)
09-23 07:35:57.694 27901 27901 E AndroidRuntime: 	at android.app.Activity.onMenuItemSelected(Activity.java:4275)
09-23 07:35:57.694 27901 27901 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:352)
09-23 07:35:57.694 27901 27901 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:264)
09-23 07:35:57.694 27901 27901 E AndroidRuntime: 	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
09-23 07:35:57.694 27901 27901 E AndroidRuntime: 	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
09-23 07:35:57.694 27901 27901 E AndroidRuntime: 	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:65)
09-23 07:35:57.694 27901 27901 E AndroidRuntime: 	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:208)
09-23 07:35:57.694 27901 27901 E AndroidRuntime: 	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
09-23 07:35:57.694 27901 27901 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
09-23 07:35:57.694 27901 27901 E AndroidRuntime: 	at androidx.appcompat.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:91)
09-23 07:35:57.694 27901 27901 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
09-23 07:35:57.694 27901 27901 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
09-23 07:35:57.694 27901 27901 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
09-23 07:35:57.694 27901 27901 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
09-23 07:35:57.694 27901 27901 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1210)
09-23 07:35:57.694 27901 27901 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3202)
09-23 07:35:57.694 27901 27901 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
09-23 07:35:57.694 27901 27901 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-23 07:35:57.694 27901 27901 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:233)
09-23 07:35:57.694 27901 27901 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8010)
09-23 07:35:57.694 27901 27901 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-23 07:35:57.694 27901 27901 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
09-23 07:35:57.694 27901 27901 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
09-23 07:35:57.699  1737  8983 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
09-23 07:35:57.700  1737 17020 W ActivityTaskManager:   Force finishing activity org.liberty.android.freeotpplus/org.fedorahosted.freeotp.ui.MainActivity
09-23 07:35:57.700  1737  8983 D FrameworkEventCollector: recordAppIssue PN: org.liberty.android.freeotpplus
09-23 07:35:57.701  1737  3513 D gwy     : OS Event: crash
09-23 07:35:57.705  1737  8983 D DropBoxManagerService: Copy /data/system/dropbox/data_app_crash@2021-09-23-07_35_57_704.txt to /data/oem_log/
09-23 07:35:57.706  1737 17020 E ScreenModeService: getAppToken ActivityRecord{92315f6 u0 net.oneplus.launcher/.Launcher t8956}
09-23 07:35:57.706  1737 17020 E ScreenModeService: setRefreshRate token ActivityRecord{92315f6 u0 net.oneplus.launcher/.Launcher t8956} rate 0 tmpRate 0
09-23 07:35:57.706  1737 17020 D OpQuickReply: setQuickReplyResumed focusedApp ActivityRecord{92315f6 u0 net.oneplus.launcher/.Launcher t8956} pkgName net.oneplus.launcher
09-23 07:35:57.706  1737 17020 D Hypnus  : hypnusSetScene: uid=10194, pid=28201, name=net.oneplus.launcher, activity=null
09-23 07:35:57.706 28883 28890 E Parcel  : Reading a NULL string not supported here.
09-23 07:35:57.707 28883 28885 E horae   : setForegroundPackage, mChargingStateMachine is null!
09-23 07:35:57.725  1737  5118 E FrameEvents: updateAcquireFence: Did not find frame.
09-23 07:35:57.728  1737 17020 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
09-23 07:35:57.738  1737  5418 E ActivityThread: Failed to find provider info for net.oneplus.odm.provider.PayloadProvider
09-23 07:35:57.738  1737  5418 E xne     : Unknown URL content://net.oneplus.odm.provider.PayloadProvider/OP_payload_upload_table
09-23 07:35:57.744  1737  2035 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
09-23 07:35:57.745  1737  2035 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
09-23 07:35:57.760  1737  2026 E system_server: Invalid ID 0x00000000.
09-23 07:35:57.764  1737  2026 I chatty  : uid=1000(system) android.ui identical 1 line
09-23 07:35:57.769  1737  2026 E system_server: Invalid ID 0x00000000.
09-23 07:35:57.770  1737  3555 D skia    : got procName system_server for pid 1737
09-23 07:35:57.771  1737  2026 E system_server: Invalid ID 0x00000000.
09-23 07:35:57.772  1737  2026 I chatty  : uid=1000(system) android.ui identical 4 lines
09-23 07:35:57.773  1737  2026 E system_server: Invalid ID 0x00000000.
09-23 07:35:57.797 31521 31591 I BtGatt.ScanManager: msg.what = 6
09-23 07:35:57.799   651   651 E SELinux : avc:  denied  { find } for pid=10276 uid=10201 name=tethering scontext=u:r:vendor_systemhelper_app:s0:c512,c768 tcontext=u:object_r:tethering_service:s0 tclass=service_manager permissive=0
09-23 07:35:57.804  1737  3555 D skia    : got procName system_server for pid 1737
09-23 07:35:57.811   986   986 D vendor.qti.bluetooth@1.0-ibs_handler: SerialClockVote: vote for UART CLK ON
09-23 07:35:57.811  1737  2026 V WindowManager: Orientation start waiting for draw, mDrawState=DRAW_PENDING in Window{99aa097 u0 Application Error: org.liberty.android.freeotpplus}, surfaceController Surface(name=Application Error: org.liberty.android.freeotpplus)/@0x6357fa
09-23 07:35:57.811   986   986 D vendor.qti.bluetooth@1.0-wake_lock: Acquire wakelock is acquired 
09-23 07:35:57.811   986   986 I vendor.qti.bluetooth@1.0-ibs_handler: DeviceWakeUp: Writing IBS_WAKE_IND
09-23 07:35:57.812 31521 31604 E bt_osi_wakelock: wakelock_acquire wakelock acquired
09-23 07:35:57.814 31521 31552 E bt_osi_wakelock: wakelock_release wakelock released
09-23 07:35:57.819 31293 31307 W System  : A resource failed to call release. 
09-23 07:35:57.835  1737  2026 D DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@476d1ab[freeotpplus]
09-23 07:35:57.839  1737  2026 D ViewRootImpl[freeotpplus]: windowFocusChanged hasFocus=true inTouchMode=true
09-23 07:35:57.843 31293 31293 D PhoneStatusBarView: getCompatMode: mode:0 ops:3
09-23 07:35:57.843 31293 31293 I PhoneStatusBarView: isFullAndNotchEnabled() isFullMode=false pkg=android isCameraNotchIgnoreSetting=false, uid=1000

```

**Comment by helloworld1** [comment]
Right, the log is very helpful. It indicates a different issue that I have never seen before. The app relies on Android system file browser (document provider) to create and select files. It should always exists on the system.

**Comment by helloworld1** [comment]
The crash issue @mateusz-bak is addressed inhttps://github.com/helloworld1/FreeOTPPlus/commit/d04e16d6f6b13b372ebac7a28d0ecb82e027a4e4
However the underlying issue is due to OS's file browser availability, which should be standard according to Android's SAF documentation https://developer.android.com/guide/topics/providers/document-provider. The app will now display an error message instead of crashing.

**Comment by helloworld1** [comment]
I am not sure about the issue @meersjo  reported. Is the crash due to the same reason, and was the debug build I posted early solve the problem?

**Comment by meersjo** [comment]
I just had a chance to test the debug build - importing the old backup (json) works fine; export crashes in both formats.

**Comment by helloworld1** [comment]
@meersjo I have found an issue when exporting. The issue should be now fixed in https://github.com/helloworld1/FreeOTPPlus/commit/c2d5b493a531febbc2e11f9b4c3f605f168527dd

You can try the new debug build with this fix:
https://drive.google.com/file/d/19gc3ZE4u3TBIEVEkpz2I1Lk_xgD9BKvZ/view?usp=sharing

Thanks again for testing and reporting.
