### ISSUE TITLE
APK version 2.8 fails the signature checks

### ISSUE THREAD

**Issue by GitHubForSnap** [helloworld1/FreeOTPPlus#203]
Hi,

I couldn't install the latest apk (version 2.8) on Android 12.1.
It fails the signature checks.

It works fine on Android 8.1.

Could you have a look?

Thank you

Here is the logcat:

```
05-05 08:06:05.720  1492  2128 I PackageParsing: org.liberty.android.freeotpplus: compat added android.permission.OTHER_SENSORS
05-05 08:06:05.839  1492  2128 W RuleEvaluation: Integrity rule files are not available.
05-05 08:06:05.840  1492  1799 I PackageManager: Integrity check passed for file:///data/app/vmdl607900143.tmp
05-05 08:06:05.846  1492  1799 I PackageParsing: org.liberty.android.freeotpplus: compat added android.permission.OTHER_SENSORS
05-05 08:06:05.855  1492  1776 I ActivityManager: Force stopping org.liberty.android.freeotpplus appid=10181 user=-1: installPackageLI
05-05 08:06:05.858  1492  1799 W PackageManager: Scanning Failed.
05-05 08:06:05.858  1492  1799 W PackageManager: com.android.server.pm.PackageManagerException: No signature found in package of version 2 or newer for package org.liberty.android.freeotpplus
05-05 08:06:05.858  1492  1799 W PackageManager: 	at com.android.server.pm.PackageManagerService.assertPackageIsValid(PackageManagerService.java:15205)
05-05 08:06:05.858  1492  1799 W PackageManager: 	at com.android.server.pm.PackageManagerService.scanPackageNewLI(PackageManagerService.java:14013)
05-05 08:06:05.858  1492  1799 W PackageManager: 	at com.android.server.pm.PackageManagerService.scanPackageTracedLI(PackageManagerService.java:13773)
05-05 08:06:05.858  1492  1799 W PackageManager: 	at com.android.server.pm.PackageManagerService.installPackagesLI(PackageManagerService.java:20005)
05-05 08:06:05.858  1492  1799 W PackageManager: 	at com.android.server.pm.PackageManagerService.installPackagesTracedLI(PackageManagerService.java:19371)
05-05 08:06:05.858  1492  1799 W PackageManager: 	at com.android.server.pm.PackageManagerService.lambda$processInstallRequestsAsync$48$PackageManagerService(PackageManagerService.java:17438)
05-05 08:06:05.858  1492  1799 W PackageManager: 	at com.android.server.pm.PackageManagerService$$ExternalSyntheticLambda57.run(Unknown Source:6)
05-05 08:06:05.858  1492  1799 W PackageManager: 	at android.os.Handler.handleCallback(Handler.java:938)
05-05 08:06:05.858  1492  1799 W PackageManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-05 08:06:05.858  1492  1799 W PackageManager: 	at android.os.Looper.loopOnce(Looper.java:201)
05-05 08:06:05.858  1492  1799 W PackageManager: 	at android.os.Looper.loop(Looper.java:288)
05-05 08:06:05.858  1492  1799 W PackageManager: 	at android.os.HandlerThread.run(HandlerThread.java:67)
05-05 08:06:05.858  1492  1799 W PackageManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
```

**Comment by helloworld1** [comment]
I have updated the APK file. Now it should surely work. The previous release was signed using the old jarsigner
