### ISSUE TITLE
FreeOTP+ crashes on QR codes that aren't valid OTP codes

### ISSUE THREAD

**Issue by strugee** [helloworld1/FreeOTPPlus#34]
STR:

1. Find a QR code that isn't properly formatted as an OTP code - Stripe generated an invalid QR code for me but for obvious reasons I don't want to put that up on GitHub; https://duckduckgo.com/?q=!qrcode+strugee.net&t=ffab&ia=answer reproduces this just fine instead
2. Start FreeOTP+ and use the option to scan the QR code
3. Point the camera at the QR code on the screen
4. Crash

Here's the stack trace I pulled from adb:

```
05-07 03:50:14.354 32075 32075 D AndroidRuntime: Shutting down VM
05-07 03:50:14.355 32075 32075 E AndroidRuntime: FATAL EXCEPTION: main
05-07 03:50:14.355 32075 32075 E AndroidRuntime: Process: org.liberty.android.freeotpplus, PID: 32075
05-07 03:50:14.355 32075 32075 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
05-07 03:50:14.355 32075 32075 E AndroidRuntime: 	at org.fedorahosted.freeotp.Token.<init>(Token.java:60)
05-07 03:50:14.355 32075 32075 E AndroidRuntime: 	at org.fedorahosted.freeotp.Token.<init>(Token.java:190)
05-07 03:50:14.355 32075 32075 E AndroidRuntime: 	at org.fedorahosted.freeotp.Token.<init>(Token.java:194)
05-07 03:50:14.355 32075 32075 E AndroidRuntime: 	at org.fedorahosted.freeotp.TokenPersistence.addWithToast(TokenPersistence.java:38)
05-07 03:50:14.355 32075 32075 E AndroidRuntime: 	at org.fedorahosted.freeotp.add.ScanActivity$1.onPostExecute(ScanActivity.java:101)
05-07 03:50:14.355 32075 32075 E AndroidRuntime: 	at org.fedorahosted.freeotp.add.ScanActivity$1.onPostExecute(ScanActivity.java:97)
05-07 03:50:14.355 32075 32075 E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:695)
05-07 03:50:14.355 32075 32075 E AndroidRuntime: 	at android.os.AsyncTask.-wrap1(Unknown Source:0)
05-07 03:50:14.355 32075 32075 E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
05-07 03:50:14.355 32075 32075 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-07 03:50:14.355 32075 32075 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
05-07 03:50:14.355 32075 32075 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
05-07 03:50:14.355 32075 32075 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-07 03:50:14.355 32075 32075 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
05-07 03:50:14.355 32075 32075 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
05-07 03:50:14.370   894  2453 W ActivityManager:   Force finishing activity org.liberty.android.freeotpplus/org.fedorahosted.freeotp.add.ScanActivity
```

**Comment by helloworld1** [comment]
The crash was fixed in this commit: 3f11114b88253d3ba0cde72b01d9821610eddcc5
Thanks for reporting.
