### ISSUE TITLE
Crash on QR code treatment

### ISSUE THREAD

**Issue by Porkepix** [helloworld1/FreeOTPPlus#69]
Crash was first experienced on 1.6, I updated to 1.7 after reading about some other similar issues and still have the crash. When starting the QR code scanner feature, there's no issue, we can see what the camera is filming. However, once focusing a QR code and it's recognized as a QR code, the crash happens.

Platform is an Android M (6.0.1) with constructor ROM.

Here's the ` adb logcat -v threadtime` of the crash:

```
01-04 12:10:32.274 27205 27562 E AndroidRuntime: FATAL EXCEPTION: pool-2-thread-4
01-04 12:10:32.274 27205 27562 E AndroidRuntime: Process: org.liberty.android.freeotpplus, PID: 27205
01-04 12:10:32.274 27205 27562 E AndroidRuntime: java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
01-04 12:10:32.274 27205 27562 E AndroidRuntime: 	at com.google.zxing.qrcode.detector.FinderPatternFinder.selectBestPatterns(FinderPatternFinder.java:616)
01-04 12:10:32.274 27205 27562 E AndroidRuntime: 	at com.google.zxing.qrcode.detector.FinderPatternFinder.find(FinderPatternFinder.java:164)
01-04 12:10:32.274 27205 27562 E AndroidRuntime: 	at com.google.zxing.qrcode.detector.Detector.detect(Detector.java:81)
01-04 12:10:32.274 27205 27562 E AndroidRuntime: 	at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
01-04 12:10:32.274 27205 27562 E AndroidRuntime: 	at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:64)
01-04 12:10:32.274 27205 27562 E AndroidRuntime: 	at org.fedorahosted.freeotp.util.TokenQRCodeDecoder.parseQRCode(TokenQRCodeDecoder.kt:49)
01-04 12:10:32.274 27205 27562 E AndroidRuntime: 	at org.fedorahosted.freeotp.ui.ScanTokenActivity.analyzeImage(ScanTokenActivity.kt:160)
01-04 12:10:32.274 27205 27562 E AndroidRuntime: 	at org.fedorahosted.freeotp.ui.ScanTokenActivity.access$analyzeImage(ScanTokenActivity.kt:39)
01-04 12:10:32.274 27205 27562 E AndroidRuntime: 	at org.fedorahosted.freeotp.ui.ScanTokenActivity$startCamera$2.analyze(ScanTokenActivity.kt:97)
01-04 12:10:32.274 27205 27562 E AndroidRuntime: 	at androidx.camera.core.ImageAnalysisAbstractAnalyzer.analyzeImage(ImageAnalysisAbstractAnalyzer.java:56)
01-04 12:10:32.274 27205 27562 E AndroidRuntime: 	at androidx.camera.core.ImageAnalysisNonBlockingAnalyzer$1.run(ImageAnalysisNonBlockingAnalyzer.java:138)
01-04 12:10:32.274 27205 27562 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
01-04 12:10:32.274 27205 27562 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
01-04 12:10:32.274 27205 27562 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by helloworld1** [comment]
Got it. Looks like ZXing bug or something.  I need to investigate further.

**Comment by helloworld1** [comment]
The issue should be fixed with this commit https://github.com/helloworld1/FreeOTPPlus/commit/8cc76e3c385db515292b003abd8e385b3b2289de
